var aqCalendar={Show:function(s,x,n){var q=new Date,c=q.getFullYear()-10,f,a,g,h,l,y=document.getElementById(x).getBoundingClientRect();void 0!=document.getElementById("aqCalendarMod1")&&document.getElementById("aqCalendarMod1").parentNode.removeChild(document.getElementById("aqCalendarMod1"));var d=document.createElement("div");d.id="aqCalendarMod1";var p=document.createElement("div");p.id="aqCalendarWrapMod1";p.innerHTML='<div class="aqYearListMod1"><div id="aqYearLeftMod1">&#8249;</div><div id="aqYearRightMod1">&#8250;</div></div>';
var e=document.createElement("table");e.id="aqCalendarYearMod1";d.appendChild(p);p.appendChild(e);document.body.appendChild(d);switch(n){case 1:for(n=0;5>n;n++){f=e.insertRow(n);for(var t=0;4>t;t++)a=f.insertCell(t),a.innerHTML=c,q.getFullYear()==c?a.className="aqToYear":a.className="aqYear",c++,a.onclick=function(){g=this.innerHTML;u()}}document.getElementById("aqYearRightMod1").onclick=function(){e.innerHTML="";for(var k=0;5>k;k++){f=e.insertRow(k);for(var b=0;4>b;b++)a=f.insertCell(b),a.innerHTML=
c,q.getFullYear()==c?a.className="aqToYear":a.className="aqYear",c++,a.onclick=function(){g=this.innerHTML;u()}}};document.getElementById("aqYearLeftMod1").onclick=function(){e.innerHTML="";c-=40;for(var k=0;5>k;k++){f=e.insertRow(k);for(var b=0;4>b;b++)a=f.insertCell(b),a.innerHTML=c,q.getFullYear()==c?a.className="aqToYear":a.className="aqYear",c++,a.onclick=function(){g=this.innerHTML;u()}}};var v=1,z;z=setInterval(function(){v++;d.style.opacity=parseFloat(v/10);1<=parseFloat(v/10)&&clearInterval(z)},
75);var u=function(){var k="\u042f\u043d\u0432 \u0424\u0435\u0432 \u041c\u0430\u0440 \u0410\u043f\u0440 \u041c\u0430\u0439 \u0418\u044e\u043d \u0418\u044e\u043b \u0410\u0432\u0433 \u0421\u0435\u043d \u041e\u043a\u0442 \u041d\u043e\u044f \u0414\u0435\u043a".split(" "),b=0,c=document.createElement("table");c.id="aqCalendarMonthMod1";p.innerHTML="";p.appendChild(c);for(var w=0;4>w;w++){f=c.insertRow(w);for(var r=0;3>r;r++)a=f.insertCell(r),a.innerHTML=k[b],parseInt(q.getMonth())==b?a.className="aqToYear":
a.className="aqYear",a.id=b,b++,a.onclick=function(){h=this.id;A()}}var m=1,g;g=setInterval(function(){m++;document.getElementById("aqCalendarMonthMod1").style.opacity=parseFloat(m/10);1<=parseFloat(m/10)&&clearInterval(g)},75)},A=function(){var c=33-(new Date(g,h,33)).getDate(),b=1;h=parseInt(h)+1;var d=document.createElement("table");d.id="aqCalendarDaysMod1";p.innerHTML="";p.appendChild(d);for(var w=0;6>w;w++){f=d.insertRow(w);for(var r=0;6>r;r++)a=f.insertCell(r),a.innerHTML=b>c?"&nbsp;":b,parseInt(q.getDate())==
b?a.className="aqToYear":a.className="aqYear",b++,a.onclick=function(){l=this.innerHTML;10>h&&(h="0"+h);10>l&&(l="0"+l);"input"==document.getElementById(s).tagName.toLowerCase()?document.getElementById(s).value=g+"-"+h+"-"+l:document.getElementById(s).innerHTML=g+"-"+h+"-"+l;document.getElementById("aqCalendarMod1").parentNode.removeChild(document.getElementById("aqCalendarMod1"))}}var m=1,e;e=setInterval(function(){m++;document.getElementById("aqCalendarDaysMod1").style.opacity=parseFloat(m/10);
1<=parseFloat(m/10)&&clearInterval(e)},75)};d.style.left=y.left+document.getElementById(x).offsetWidth+10+"px";d.style.top=y.top+document.getElementById(x).offsetHeight/2-d.offsetHeight/2+"px";d.style.width="170px";break;case 2:for(n=0;5>n;n++)for(f=e.insertRow(n),t=0;4>t;t++)a=f.insertCell(t),a.innerHTML=c,q.getFullYear()==c?a.className="aqToYear":a.className="aqYear",c++,a.onclick=function(){g=this.innerHTML;u()};document.getElementById("aqYearRightMod1").onclick=function(){e.innerHTML="";for(var k=
0;5>k;k++){f=e.insertRow(k);for(var b=0;4>b;b++)a=f.insertCell(b),a.innerHTML=c,q.getFullYear()==c?a.className="aqToYear":a.className="aqYear",c++,a.onclick=function(){g=this.innerHTML;u()}}};document.getElementById("aqYearLeftMod1").onclick=function(){e.innerHTML="";c-=40;for(var k=0;5>k;k++){f=e.insertRow(k);for(var b=0;4>b;b++)a=f.insertCell(b),a.innerHTML=c,q.getFullYear()==c?a.className="aqToYear":a.className="aqYear",c++,a.onclick=function(){g=this.innerHTML;u()}}};v=1;z=setInterval(function(){v++;
d.style.opacity=parseFloat(v/10);1<=parseFloat(v/10)&&clearInterval(z)},75);u=function(){var c="\u042f\u043d\u0432 \u0424\u0435\u0432 \u041c\u0430\u0440 \u0410\u043f\u0440 \u041c\u0430\u0439 \u0418\u044e\u043d \u0418\u044e\u043b \u0410\u0432\u0433 \u0421\u0435\u043d \u041e\u043a\u0442 \u041d\u043e\u044f \u0414\u0435\u043a".split(" "),b=0,d=document.createElement("table");d.id="aqCalendarMonthMod1";p.innerHTML="";p.appendChild(d);for(var g=0;4>g;g++){f=d.insertRow(g);for(var e=0;3>e;e++)a=f.insertCell(e),
a.innerHTML=c[b],parseInt(q.getMonth())==b?a.className="aqToYear":a.className="aqYear",a.id=b,b++,a.onclick=function(){h=this.id;A()}}var m=1,l;l=setInterval(function(){m++;document.getElementById("aqCalendarMonthMod1").style.opacity=parseFloat(m/10);1<=parseFloat(m/10)&&clearInterval(l)},75)};A=function(){var c=33-(new Date(g,h,33)).getDate(),b=1;h=parseInt(h)+1;var d=document.createElement("table");d.id="aqCalendarDaysMod1";p.innerHTML="";p.appendChild(d);for(var e=0;6>e;e++){f=d.insertRow(e);for(var r=
0;6>r;r++)a=f.insertCell(r),a.innerHTML=b>c?"&nbsp;":b,parseInt(q.getDate())==b?a.className="aqToYear":a.className="aqYear",b++,a.onclick=function(){l=this.innerHTML;10>h&&(h="0"+h);10>l&&(l="0"+l);"input"==document.getElementById(s).tagName.toLowerCase()?document.getElementById(s).value=g+"-"+h+"-"+l:document.getElementById(s).innerHTML=g+"-"+h+"-"+l;document.getElementById("aqCalendarMod1").parentNode.removeChild(document.getElementById("aqCalendarMod1"))}}var m=1,n;n=setInterval(function(){m++;
document.getElementById("aqCalendarDaysMod1").style.opacity=parseFloat(m/10);1<=parseFloat(m/10)&&clearInterval(n)},75)};d.style.left=y.left+"px";d.style.top=y.top+document.getElementById(x).offsetHeight+2+"px";d.style.width=document.getElementById(s).offsetWidth-18+"px"}}};